/**
 * Data bridge: reads the pipeline's oceandex_dataset.json and generates
 * typed TypeScript modules for the app to import at build time.
 *
 * Usage: npx tsx scripts/generate-data.ts
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const DATASET_PATH = resolve(__dirname, '../../pipeline/data/oceandex_dataset.json')
const OUT_DIR = resolve(__dirname, '../src/data')

// Validate source exists
if (!existsSync(DATASET_PATH)) {
  console.error(`ERROR: Dataset not found at ${DATASET_PATH}`)
  console.error('Run the pipeline first: cd pipeline && python3 run_pipeline.py')
  process.exit(1)
}

console.log(`Reading dataset from ${DATASET_PATH}...`)
const raw = JSON.parse(readFileSync(DATASET_PATH, 'utf-8'))

const species = raw.species as Record<string, unknown>[]
const diveSites = raw.dive_sites as Record<string, unknown>[]
const metadata = raw.metadata as Record<string, unknown>

console.log(`  Species: ${species.length}`)
console.log(`  Dive sites: ${diveSites.length}`)

// Clean species: strip extra fields, assign IDs to species missing them
const SPECIES_FIELDS = [
  'id', 'scientific_name', 'common_name_en', 'common_name_es',
  'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'species',
  'category', 'observation_count', 'inat_observations',
  'primary_photo', 'additional_photos', 'wikipedia_url', 'worms_authority',
  'sightability_score', 'sightability_tier',
]

let nextId = Math.max(...species.map((s: any) => s.id ?? 0)) + 1
const cleanSpecies = species.map((s: any) => {
  const clean: Record<string, unknown> = {}
  for (const key of SPECIES_FIELDS) {
    clean[key] = s[key] ?? null
  }
  // Assign auto-ID for species without one (e.g. nudibranchs from iNat)
  if (clean.id == null) {
    clean.id = nextId++
  }
  // Ensure numeric fields are numbers
  clean.observation_count = clean.observation_count ?? 0
  clean.inat_observations = clean.inat_observations ?? 0
  clean.sightability_score = clean.sightability_score ?? 0
  clean.sightability_tier = clean.sightability_tier ?? 'unlikely'
  // Ensure arrays
  clean.additional_photos = clean.additional_photos ?? []
  return clean
})

// Generate species.ts
const speciesOut = `// Auto-generated by scripts/generate-data.ts — DO NOT EDIT
import type { Species } from './types'

export const species: Species[] = ${JSON.stringify(cleanSpecies, null, 2)}

export const speciesById = new Map<number, Species>(
  species.map((s) => [s.id, s])
)
`

writeFileSync(resolve(OUT_DIR, 'species.ts'), speciesOut, 'utf-8')
console.log(`  Written: src/data/species.ts`)

// Generate diveSites.ts
const diveSitesOut = `// Auto-generated by scripts/generate-data.ts — DO NOT EDIT
import type { DiveSite } from './types'

export const diveSites: DiveSite[] = ${JSON.stringify(diveSites, null, 2)} as const satisfies DiveSite[]
`

writeFileSync(resolve(OUT_DIR, 'diveSites.ts'), diveSitesOut, 'utf-8')
console.log(`  Written: src/data/diveSites.ts`)

// Generate metadata.ts
const metadataOut = `// Auto-generated by scripts/generate-data.ts — DO NOT EDIT
import type { DatasetMetadata } from './types'

export const metadata: DatasetMetadata = ${JSON.stringify(metadata, null, 2)}
`

writeFileSync(resolve(OUT_DIR, 'metadata.ts'), metadataOut, 'utf-8')
console.log(`  Written: src/data/metadata.ts`)

// Generate categories.ts (static, not from dataset)
const categoriesOut = `// Category display metadata
import type { Category } from './types'

export interface CategoryInfo {
  id: Category
  label_es: string
  label_en: string
  color: string
  emoji: string
}

export const categories: CategoryInfo[] = [
  { id: 'fish_and_vertebrates', label_es: 'Peces y vertebrados', label_en: 'Fish & vertebrates', color: 'var(--color-cat-fish)', emoji: '🐟' },
  { id: 'mollusks', label_es: 'Moluscos', label_en: 'Mollusks', color: 'var(--color-cat-mollusks)', emoji: '🐙' },
  { id: 'crustaceans', label_es: 'Crustáceos', label_en: 'Crustaceans', color: 'var(--color-cat-crustaceans)', emoji: '🦀' },
  { id: 'echinoderms', label_es: 'Equinodermos', label_en: 'Echinoderms', color: 'var(--color-cat-echinoderms)', emoji: '⭐' },
  { id: 'algae', label_es: 'Algas', label_en: 'Algae', color: 'var(--color-cat-algae)', emoji: '🌿' },
  { id: 'cnidarians', label_es: 'Cnidarios', label_en: 'Cnidarians', color: 'var(--color-cat-cnidarians)', emoji: '🪸' },
  { id: 'worms', label_es: 'Gusanos', label_en: 'Worms', color: 'var(--color-cat-worms)', emoji: '🪱' },
  { id: 'sponges', label_es: 'Esponjas', label_en: 'Sponges', color: 'var(--color-cat-sponges)', emoji: '🧽' },
]

export const categoryMap = new Map(categories.map((c) => [c.id, c]))
`

writeFileSync(resolve(OUT_DIR, 'categories.ts'), categoriesOut, 'utf-8')
console.log(`  Written: src/data/categories.ts`)

// Summary
const withPhotos = species.filter((s: any) => s.primary_photo).length
const recommended = species.filter(
  (s: any) => s.primary_photo && (s.sightability_tier === 'common' || s.sightability_tier === 'uncommon')
).length

console.log(`\nData bridge complete:`)
console.log(`  Total species: ${species.length}`)
console.log(`  With photos: ${withPhotos}`)
console.log(`  Recommended v1: ${recommended}`)
console.log(`  Dive sites: ${diveSites.length}`)
